site_name: My Blog - Tenax
theme:
  name: material
  font:
    text: Inter
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

  language: zh
  
  palette:
    #Light Mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: green
      accent: green

    #Dark Mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: black
      accent: deep purple

nav:
  - Blog:
      - blog/posts/Material_for_MkDocs_configuration_and_deployment.md

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: http://gitlab.code-nav.cn/Tenax

markdown_extensions:

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.inlinehilite

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - admonition
  - pymdownx.details
  - pymdownx.mark
  - attr_list

  - pymdownx.snippets

  - pymdownx.arithmatex:
      generic: true

  - footnotes

  - pymdownx.tabbed:
      alternate_style: true



copyright: Copyright &copy; 2024 <a href="http://gitlab.code-nav.cn/Tenax"  target="_blank" rel="noopener">Tenax</a>

extra_css:
  - stylesheets/extra.css