site_name: My Blog - Tenax
site_url: https://a53d90dd.tenax-756.pages.dev
theme:
  name: material
  custom_dir: overrides
  font:
    text: Inter
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.indexes
    - navigation.tracking
    - search.share
    - navigation.top
    # - navigation.tabs
    - navigation.sections
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - toc.follow

  language: zh

  palette:
    #Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: green
      accent: green

    #Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: black
      accent: deep purple

plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      post_url_format: "{slug}"
  - glightbox
  - minify:
      minify_html: true

  # - privacy // Conflict with giscus

  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      tags_file: tags.md
  - git-committers:
      enabled: true
      repository: Tenax-599/mkdocs-material
      branch: main
      token: !ENV GH_TOKEN
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: false
      enable_creation_date: true
      enabled: true

# hooks:
#   - hooks/socialmedia.py

# nav:
#   - Blog:
#       - blog/posts/Material_for_MkDocs_configuration_and_deployment.md
#       - blog/posts/Xiaomi AX3000T Brush with ImmortalWrt and U-Boot.md

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: http://gitlab.code-nav.cn/Tenax

markdown_extensions:

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.inlinehilite

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - admonition
  - pymdownx.details
  - pymdownx.mark
  - attr_list

  - pymdownx.snippets

  - pymdownx.arithmatex:
      generic: true

  - footnotes
  - md_in_html

  # - pymdownx.tabbed:
  #     alternate_style: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

copyright: Copyright &copy; 2024 <a href="http://gitlab.code-nav.cn/Tenax"  target="_blank" rel="noopener">Tenax</a>